spring:
  cloud:
    nacos:
      # Nacos 作为注册中心的配置项，对应 NacosDiscoveryProperties 配置类
      discovery:
        server-addr: localhost:8848 # Nacos 服务器地址
  application:
    name: concurrency-practice

server:
  port: 91
